export const PLAYER_MOVE = 'PLAYER_MOVE'
export const BOT_MOVE = 'BOT_MOVE'
export const BOARD = 'BOARD'
export const TURN = 'TURN'
export const RESET = 'RESET'
export const CHANGE_SIDE = 'CHANGE_SIDE'
